repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: [--django]
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.11.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v0.7.1
    hooks:
      - id: add-trailing-comma
